import React from "react";
import ReactMarkdown from "react-markdown";
import { renderToStaticMarkup } from "react-dom/server";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import remarkGfm from "remark-gfm";
import formatAIText from "./formatAIText";

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  }[c]));
}

function renderMarkdown(markdown) {
  return renderToStaticMarkup(
    <ReactMarkdown
      remarkPlugins={[remarkMath, remarkGfm]}
      rehypePlugins={[[rehypeKatex, { output: "mathml", throwOnError: false }]]}
    >
      {formatAIText(markdown)}
    </ReactMarkdown>
  );
}

const BASE_CSS = `
  @page { size: A4; margin: 15mm; }
  * { box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif; max-width: 780px; margin: 0 auto; color: #1a202c; line-height: 1.65; }
  h1 { font-size: 1.5rem; margin: 0 0 2px; }
  h2 { font-size: 1.1rem; margin: 1.3em 0 0.45em; color: #1d4ed8; break-after: avoid; }
  h3 { font-size: 1rem; margin: 1.1em 0 0.35em; break-after: avoid; }
  p { margin: 0.5em 0; }
  ul, ol { padding-left: 1.5em; }
  table { border-collapse: collapse; margin: 10px 0; width: 100%; }
  th, td { border: 1px solid #cbd5e1; padding: 6px 10px; text-align: left; }
  math { font-family: "Cambria Math", "STIX Two Math", "Latin Modern Math", serif; }
  blockquote { border-left: 3px solid #cbd5e1; margin: 1em 0; padding-left: 1em; color: #475569; }
  code { background: #f1f5f9; padding: 2px 5px; border-radius: 4px; font-size: 0.9em; }
  pre { background: #f8fafc; border: 1px solid #e2e8f0; padding: 12px; overflow-x: auto; border-radius: 6px; }
  .sheet-header { border-bottom: 2px solid #0a3339; padding-bottom: 10px; margin-bottom: 1.4em; }
  .sheet-chapter { color: #64748b; font-size: 0.95rem; }
  .sheet-footer { margin-top: 2em; padding-top: 1em; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.8rem; }
  @media print {
    h1, h2, h3 { break-after: avoid; }
  }
`;

function buildDoc({ title, subtitle, bodyHtml }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${escapeHtml(title)}</title>
<style>${BASE_CSS}</style>
</head>
<body>
<div class="sheet-header">
  <h1>${escapeHtml(title)}</h1>
  ${subtitle ? `<div class="sheet-chapter">${escapeHtml(subtitle)}</div>` : ""}
</div>
${bodyHtml}
<p class="sheet-footer">Generated by StudyBuddy</p>
</body>
</html>`;
}

function openPrintDoc(doc, onBlocked) {
  const win = window.open("", "_blank");
  if (!win) {
    if (onBlocked) onBlocked();
    return;
  }
  win.document.open();
  win.document.write(doc);
  win.document.close();
  win.focus();
  setTimeout(() => {
    try { win.print(); } catch {
      /* ignore */
    }
  }, 400);
  setTimeout(() => {
    try { win.close(); } catch {
      /* ignore */
    }
  }, 60000);
}

export function downloadAsPdf({ title, subtitle = "", markdown = "", bodyHtml = "" }) {
  if (markdown) bodyHtml = renderMarkdown(markdown);
  if (!bodyHtml) return;
  const doc = buildDoc({ title, subtitle, bodyHtml });
  openPrintDoc(doc);
}

export function downloadAsMarkdown({ filename, title, subtitle = "", markdown = "" }) {
  if (!markdown) return;
  const content = `# ${title}${subtitle ? `\n\n${subtitle}` : ""}\n\n${formatAIText(markdown).trim()}\n`;
  downloadTextFile(filename, content);
}

export function downloadTextFile(filename, content) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export const renderMarkdownHtml = renderMarkdown;
